### ISSUE TITLE
Style Encrypt / Decrypt / Grant Access Options to Tabs

### ISSUE THREAD

**Issue by jza201** [jza201/frdr-secure-data#12]
Change the options to look like tabs. 
Is this style an acceptable option? https://www.w3schools.com/w3css/w3css_tabulators.asp

**Comment by axfelix** [comment]
Definitely, I think that works great. Maybe we can keep the colour coding on the bottom buttons at that point.

**Comment by jza201** [comment]
Does this look good to you? I also tried some styles in bootstrap. I think this one looks best to me. Choosing the style colour is a pain. 
![image](https://user-images.githubusercontent.com/26235948/85081946-53eb0f00-b182-11ea-8966-40e52951fa30.png)
![image](https://user-images.githubusercontent.com/26235948/85082074-aa584d80-b182-11ea-9af6-2cd2fcd410e7.png)
![image](https://user-images.githubusercontent.com/26235948/85081974-649b8500-b182-11ea-954a-0d206760ab22.png)

**Comment by axfelix** [comment]
Yeah, I like it a lot, actually!

I know neither of us are really frontend people but I think this eliminates any confusion and looks good.
