### ISSUE TITLE
Can't switch back to encrypt mode after toggling to grant access mode

### ISSUE THREAD

**Issue by axfelix** [jza201/frdr-secure-data#3]
Will have to play around with this a bit more to make sure I can duplicate regularly, I suspect it's something to do with the encrypt mode also being set as the main/default/first window. Also, this may be irrelevant if we change the window switching behaviour as discussed in https://github.com/jza201/frdr-secure-data/issues/2

**Comment by jza201** [comment]
I will close this one as we changed to one main window as discussed in #2.
