### ISSUE TITLE
Process should probably fully terminate and clean up when closing the app window

### ISSUE THREAD

**Issue by axfelix** [jza201/frdr-secure-data#6]
Right now the process doesn't fully terminate Electron and Python when closing the app window -- I know this default behaviour varies across systems and macOS will leave apps running in the background by default, but for a single window I think it makes sense to clean up on close.

It's not always clear how to do this with Electron and `mainWindow`, but I have it working the way I've implemented `before-quit` in https://github.com/axfelix/moveit-electron/blob/master/gui/main.js.

**Comment by jza201** [comment]
This is easy to fix. I removed a `preventDefault()` call when closing window.
